<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
      <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Hiragino-Sans-GB-W3.otf" />
    <None Remove="Fonts\NotoSansJP-Light.ttf" />
    <None Remove="Fonts\NotoSansJP-Medium.ttf" />
    <None Remove="Fonts\NotoSansJP-Regular.ttf" />
    <None Remove="Fonts\NotoSansJP-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.3" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\NotoSansJP-Light.ttf" />
    <Resource Include="Fonts\NotoSansJP-Medium.ttf" />
    <Resource Include="Fonts\NotoSansJP-Regular.ttf" />
    <Resource Include="Fonts\NotoSansJP-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPUBParser\EPUBParser.csproj" />
    <ProjectReference Include="..\JapaneseDictionary\JapaneseDictionary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
