//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WactonWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WactonWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///
        ///ヽ
        ///
        ///repetition mark in katakana
        ///
        ///0
        ///
        ///ヾ
        ///
        ///voiced repetition mark in katakana
        ///
        ///0
        ///
        ///ゝ
        ///
        ///repetition mark in hiragana
        ///
        ///0
        ///
        ///ゞ
        ///
        ///voiced repetition mark in hiragana
        ///
        ///0
        ///〃
        ///
        ///おなじ
        ///おなじく
        ///
        ///ditto mark
        ///
        ///0
        ///仝
        ///
        ///どうじょう
        ///
        ///&quot;as above&quot; mark
        ///
        ///0
        ///々
        ///
        ///のま
        ///ノマ
        ///
        ///kanji iteration mark
        ///
        ///0
        ///漢数字ゼロ
        ///
        ///かんすうじゼロ
        ///
        ///&quot;kanji&quot; zero
        ///
        ///0
        ///○
        ///〇
        ///
        ///まる
        ///
        ///circle (sometimes used for zero)
        ///&apos;correct&apos; (when marking)
        ///symbol used as a placeholder (either because a number of other words could be used in that position, or b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dict {
            get {
                return ResourceManager.GetString("Dict", resourceCulture);
            }
        }
    }
}
